EXECUTION:
  MODEL_SERVING: None
  EPOCHS: 120
  TEST_FREQUENCY: 5
  OPTIMIZER_BUILDER: VAEGANOptimizerBuilder
  MODEL_BUILDER: vaegan_model_builder 
  TRAINER: VAEGANTrainer
  DATASET_PRELOAD: "CIFAR10"
  DATASET_PRELOAD_CLASS: [0]
  DATASET_TEST_PRELOAD_CLASS: [1,2,3,4,5,6,7,8,9]


SAVE:
  MODEL_VERSION: 1
  MODEL_CORE_NAME: "ablation_reid"
  MODEL_BACKBONE: "res50"
  MODEL_QUALIFIER: "all"
  DRIVE_BACKUP: True
  SAVE_FREQUENCY: 5 # Epoch

DATASET:
  ROOT_DATA_FOLDER: "VeRi"
  TRAIN_FOLDER: "image_train"
  TEST_FOLDER: "image_test"
  QUERY_FOLDER: "image_query"
  SHAPE: [32,32]

TRANSFORMATION:
  NORMALIZATION_MEAN: 0.5
  NORMALIZATION_STD: 0.5
  NORMALIZATION_SCALE: 255.0
  H_FLIP: 0.5
  T_CROP: True
  RANDOM_ERASE: True
  RANDOM_ERASE_VALUE: 0.5
  CHANNELS: 3
  BATCH_SIZE: 32
  WORKERS: 1

MODEL:
  BASE: 32
  ARCH: "VAEGAN"
  LATENT_DIMENSIONS: 128
  MODEL_KWARGS: '{"channels":3}'


OPTIMIZER:
  OPTIMIZER_NAME: "Adam"
  OPTIMIZER_KWARGS: '{"betas":[0.5, 0.999]}'
  BASE_LR: 0.0001
  LR_BIAS_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_BIAS_FACTOR: 0.0005
  FP16: True

SCHEDULER:
  LR_SCHEDULER: 'StepLR'
  LR_KWARGS: '{"step_size":30, "gamma":0.25}'
  

LOGGING:
  STEP_VERBOSE: 100 # Batch